# Generated by Django 5.2.3 on 2025-06-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bed",
            name="rent_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
