# Generated by Django 5.2.3 on 2025-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bed_deposit_amount_bed_rent_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bed",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="bed",
            name="rent_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
