# Generated by Django 5.2.3 on 2025-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_bed_deposit_amount_alter_bed_rent_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(),
        ),
    ]
