# Generated by Django 5.2.3 on 2025-07-05 07:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_bed_room_number_bed_token_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="for_month",
            field=models.CharField(
                blank=True, choices=core.models.default_months, max_length=10
            ),
        ),
    ]
