# Generated by Django 5.2.3 on 2025-07-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_payment_for_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(default="vaibhav", max_length=40),
        ),
    ]
