# Generated by Django 5.2.3 on 2025-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_customuser_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(max_length=40),
        ),
    ]
