# Generated by Django 5.2.3 on 2025-07-06 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_customuser_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_name",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                help_text="Full name (e.g., Vaibhav Sharma)",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username may contain letters, digits, spaces and @/./+/-/_ characters.",
                        regex="^[\\w\\s.@+-]+$",
                    )
                ],
            ),
        ),
    ]
