# Generated by Django 5.2.3 on 2025-07-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_customuser_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
