# Generated by Django 5.2.3 on 2025-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bed_photos",
            field=models.JSONField(
                blank=True, default=list, help_text="List of image URLs"
            ),
        ),
    ]
